[package]
name = "rust_lab_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-arena = "2.0.2"
rand = "0.8.5"
nohash = "0.2.0"